
apiVersion: v1
kind: Service
metadata:
  name: grafana-service-nautilus
  namespace: grafana-monitoring-nautilus
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-nautilus
  namespace: grafana-monitoring-nautilus
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container-nautilus
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        emptyDir: {}



kubectl get ep to check endpoints are created properly for your deployment.


